use crate::parser::{
    CallSyntax, Expr, ExprKind, Program, first_tuple_location, parse, program_contains_tuple,
    validate_parameter_declarations,
};
use crate::primitive::{analyze, resolve_names};
use crate::{
    Error, ErrorKind, EvaluationConfiguration, ProgramResult, ScalarType, Type, Value,
    evaluate_source_with_configuration, format_value,
};
use std::fmt::Write;

#[derive(Clone, Debug, PartialEq)]
pub struct CEmissionResult {
    pub source: String,
}

pub fn emit_c_source(source: &str) -> Result<CEmissionResult, Error> {
    emit_c_source_with_configuration(source, EvaluationConfiguration::default())
}

pub fn emit_c_source_with_configuration(
    source: &str,
    configuration: EvaluationConfiguration,
) -> Result<CEmissionResult, Error> {
    let _ = crate::resources::ResourceContext::new(
        configuration.profile,
        configuration.limits,
        configuration.allocation_failure,
    )?;
    let program = parse(source)?;
    validate_parameter_declarations(&program)?;
    resolve_names(&program)?;
    if program_contains_tuple(&program) {
        let first = first_tuple_location(&program).unwrap_or_else(crate::SourceLocation::start);
        crate::resources::ResourceContext::new(
            configuration.profile,
            configuration.limits,
            configuration.allocation_failure,
        )?
        .require_tuple_profile(first)?;
    }
    let _ = analyze(&program)?;
    if program.parameters.is_empty() {
        return match evaluate_source_with_configuration(source, configuration) {
            Ok(result) => emit_constant_program(&result),
            Err(error)
                if matches!(
                    error.kind,
                    ErrorKind::DomainError | ErrorKind::ResourceError | ErrorKind::ShapeMismatch
                ) =>
            {
                Ok(CEmissionResult {
                    source: runtime_failure_program(&error),
                })
            }
            Err(error) => Err(error),
        };
    }
    emit_parameterized_program(&program, configuration)
}

fn emit_constant_program(result: &ProgramResult) -> Result<CEmissionResult, Error> {
    let mut output = String::new();
    for value in &result.values {
        output.push_str(&format_value(value)?);
        output.push('\n');
    }
    Ok(CEmissionResult {
        source: format!(
            "/* Generated by Faraweave 0.1.0. Strict C11; no runtime required. */\n\
             #include <stdio.h>\n\
             #ifdef _WIN32\n\
             #include <fcntl.h>\n\
             #include <io.h>\n\
             #endif\n\
             int main(int argc, char **argv) {{\n\
             \x20 (void)argv;\n\
             #ifdef _WIN32\n\
             \x20 if (_setmode(_fileno(stdout), _O_BINARY) == -1 || _setmode(_fileno(stderr), _O_BINARY) == -1) return 1;\n\
             #endif\n\
             \x20 if (setvbuf(stdout, NULL, _IONBF, 0) != 0) return 1;\n\
             \x20 if (argc != 1) {{\n\
             \x20   (void)fprintf(stderr, \"faraweave_argument_error reason=extra required_count=0 supplied_count=%d position=1 parameter_name=- expected_type=- declaration_span=- actual_container=- actual_type=- invalid_value_invariant=-\\n\", argc - 1);\n\
             \x20   return 1;\n\
             \x20 }}\n\
             \x20 static const char output[] = {literal};\n\
             \x20 const size_t size = sizeof(output) - 1U;\n\
             \x20 if (size != 0U) {{ const size_t accepted = fwrite(output, 1U, size, stdout);\n\
             \x20   if (accepted != size) {{ (void)fprintf(stderr, \"faraweave_output_error reason=write_failed pending_byte_count=%zu accepted_byte_count=%zu output_position=%zu\\n\", size, accepted, accepted); return 1; }}\n\
             \x20 }}\n\
             \x20 if (fflush(stdout) != 0) {{\n\
             \x20   (void)fprintf(stderr, \"faraweave_output_error reason=flush_failed pending_byte_count=%zu accepted_byte_count=%zu output_position=%zu\\n\", size, size, size); return 1;\n\
             \x20 }}\n\
             \x20 return 0;\n\
             }}\n",
            literal = c_string(&output)
        ),
    })
}

fn runtime_failure_program(error: &Error) -> String {
    let diagnostic = format!(
        "<generated>:{}:{}: {}: {}\n",
        error.location.line,
        error.location.column,
        error.kind.diagnostic_name(),
        error.message
    );
    format!(
        "/* Generated by Faraweave 0.1.0. Strict C11; no runtime required. */\n\
         #include <stdio.h>\n\
         #ifdef _WIN32\n\
         #include <fcntl.h>\n\
         #include <io.h>\n\
         #endif\n\
         int main(int argc, char **argv) {{\n\
         \x20 (void)argv;\n\
         #ifdef _WIN32\n\
         \x20 if (_setmode(_fileno(stdout), _O_BINARY) == -1 || _setmode(_fileno(stderr), _O_BINARY) == -1) return 1;\n\
         #endif\n\
         \x20 if (argc != 1) {{\n\
         \x20   (void)fprintf(stderr, \"faraweave_argument_error reason=extra required_count=0 supplied_count=%d position=1 parameter_name=- expected_type=- declaration_span=- actual_container=- actual_type=- invalid_value_invariant=-\\n\", argc - 1);\n\
         \x20   return 1;\n\
         \x20 }}\n\
         \x20 (void)fputs({}, stderr);\n\
         \x20 return 1;\n\
         }}\n",
        c_string(&diagnostic)
    )
}

struct CGenerator {
    definitions: String,
    next_id: usize,
    parameter_types: Vec<ScalarType>,
}

fn emit_parameterized_program(
    program: &Program,
    configuration: EvaluationConfiguration,
) -> Result<CEmissionResult, Error> {
    let mut generator = CGenerator {
        definitions: String::new(),
        next_id: 0,
        parameter_types: program
            .parameters
            .iter()
            .map(|parameter| parameter.scalar_type)
            .collect(),
    };
    let root_ids: Vec<usize> = program
        .roots
        .iter()
        .map(|root| generator.emit_expr(root, None))
        .collect::<Result<_, _>>()?;
    let mut source = String::from(PARAMETER_RUNTIME);
    source.push_str("\nFWV fw_parameters[");
    writeln!(source, "{}];", program.parameters.len().max(1)).map_err(|_| emission_error())?;
    source.push_str("const int fw_parameter_types[] = {");
    for parameter in &program.parameters {
        write!(
            source,
            "{},",
            match parameter.scalar_type {
                ScalarType::Bool => 0,
                ScalarType::Int => 1,
                ScalarType::Double => 2,
            }
        )
        .map_err(|_| emission_error())?;
    }
    source.push_str("0};\nconst char *const fw_parameter_names[] = {");
    for parameter in &program.parameters {
        write!(source, "{},", c_string(&parameter.name)).map_err(|_| emission_error())?;
    }
    source.push_str("\"\"};\nconst size_t fw_parameter_spans[][6] = {");
    for parameter in &program.parameters {
        write!(
            source,
            "{{{}U,{}U,{}U,{}U,{}U,{}U}},",
            parameter.span.begin.offset,
            parameter.span.begin.line,
            parameter.span.begin.column,
            parameter.span.end.offset,
            parameter.span.end.line,
            parameter.span.end.column
        )
        .map_err(|_| emission_error())?;
    }
    source.push_str("{0U,0U,0U,0U,0U,0U}};\n");
    source.push_str(&generator.definitions);
    writeln!(
        source,
        "const size_t fw_required = {}U;",
        program.parameters.len()
    )
    .map_err(|_| emission_error())?;
    writeln!(
        source,
        "const int fw_profile = {};\n\
         const int fw_has_vector_limit = {};\n\
         const size_t fw_vector_limit = {}U;\n\
         const int fw_has_tuple_limit = {};\n\
         const size_t fw_tuple_limit = {}U;\n\
         const int fw_has_live_limit = {};\n\
         const size_t fw_live_limit = {}U;\n\
         const int fw_has_work_limit = {};\n\
         const size_t fw_work_limit = {}U;\n\
         const int fw_has_failure_ordinal = {};\n\
         const size_t fw_failure_ordinal = {}U;",
        match configuration.profile {
            crate::ExecutionProfile::TrustedLocalV1 => 0,
            crate::ExecutionProfile::BoundedV1 => 1,
            crate::ExecutionProfile::TrustedLocalV2 => 2,
            crate::ExecutionProfile::BoundedV2 => 3,
        },
        i32::from(configuration.limits.max_vector_bytes.is_some()),
        configuration.limits.max_vector_bytes.unwrap_or(0),
        i32::from(configuration.limits.max_tuple_table_bytes.is_some()),
        configuration.limits.max_tuple_table_bytes.unwrap_or(0),
        i32::from(configuration.limits.max_live_evaluation_bytes.is_some()),
        configuration.limits.max_live_evaluation_bytes.unwrap_or(0),
        i32::from(configuration.limits.max_work_units.is_some()),
        configuration.limits.max_work_units.unwrap_or(0),
        i32::from(configuration.allocation_failure.fail_at_ordinal.is_some()),
        configuration
            .allocation_failure
            .fail_at_ordinal
            .unwrap_or(0),
    )
    .map_err(|_| emission_error())?;
    source.push_str("static const FWExpr fw_roots[] = {");
    for id in &root_ids {
        write!(source, "fw_expr_{id},").map_err(|_| emission_error())?;
    }
    source.push_str("NULL};\n");
    writeln!(
        source,
        "int main(int argc, char **argv) {{ return fw_main(argc, argv, {}U, fw_roots); }}",
        root_ids.len()
    )
    .map_err(|_| emission_error())?;
    Ok(CEmissionResult { source })
}

impl CGenerator {
    fn emit_expr(
        &mut self,
        expression: &Expr,
        placeholder_type: Option<&Type>,
    ) -> Result<usize, Error> {
        let child_ids = match &expression.kind {
            ExprKind::Tuple(elements) => elements
                .iter()
                .map(|element| self.emit_expr(element, placeholder_type))
                .collect::<Result<Vec<_>, _>>()?,
            ExprKind::Call { arguments, .. } => arguments
                .iter()
                .map(|argument| self.emit_expr(argument, placeholder_type))
                .collect::<Result<Vec<_>, _>>()?,
            ExprKind::Fanout { operand, branches } => {
                let operand_type =
                    static_expression_type(operand, &self.parameter_types, placeholder_type)?;
                let mut ids = vec![self.emit_expr(operand, placeholder_type)?];
                for branch in branches {
                    ids.push(self.emit_expr(branch, Some(&operand_type))?);
                }
                ids
            }
            ExprKind::Literal(_)
            | ExprKind::Vector(_, _)
            | ExprKind::DeepTuple { .. }
            | ExprKind::UnaryChain { .. }
            | ExprKind::Parameter(_)
            | ExprKind::UnresolvedName { .. }
            | ExprKind::Placeholder => Vec::new(),
        };
        let id = self.next_id;
        self.next_id += 1;
        writeln!(
            self.definitions,
            "static int fw_expr_{id}(const FWV *hole, FWV *out) {{"
        )
        .map_err(|_| emission_error())?;
        match &expression.kind {
            ExprKind::Literal(value) => self.emit_literal(value)?,
            ExprKind::Vector(element_type, elements) => {
                writeln!(
                    self.definitions,
                    "  (void)hole; if (!fw_make_vector(out, {}, {}U, 0U, \"vector_literal\", {}U, {}U)) return 0;",
                    scalar_tag(*element_type),
                    elements.len(),
                    expression.span.begin.line,
                    expression.span.begin.column
                )
                .map_err(|_| emission_error())?;
                for (index, value) in elements.iter().enumerate() {
                    writeln!(self.definitions, "  {};", vector_assignment(value, index)?)
                        .map_err(|_| emission_error())?;
                }
                self.definitions.push_str("  return 1;\n");
            }
            ExprKind::DeepTuple { .. } => return Err(emission_error()),
            ExprKind::UnaryChain { .. } => return Err(emission_error()),
            ExprKind::Tuple(elements) => {
                writeln!(
                    self.definitions,
                    "  if (!fw_make_tuple(out, {}U, \"tuple_literal\", {}U, {}U)) return 0;",
                    elements.len(),
                    expression.span.begin.line,
                    expression.span.begin.column
                )
                .map_err(|_| emission_error())?;
                for (index, child) in child_ids.iter().enumerate() {
                    writeln!(
                        self.definitions,
                        "  if (!fw_expr_{child}(hole, &out->items[{index}U])) {{ fw_free(out); return 0; }}"
                    )
                    .map_err(|_| emission_error())?;
                }
                self.definitions.push_str("  return 1;\n");
            }
            ExprKind::Parameter(index) => {
                writeln!(
                    self.definitions,
                    "  (void)hole; return fw_borrow(&fw_parameters[{index}U], out);"
                )
                .map_err(|_| emission_error())?;
            }
            ExprKind::Placeholder => {
                self.definitions
                    .push_str("  if (hole == NULL) return fw_fail(\"ValueError\", \"missing fanout placeholder\", 0U, 0U); return fw_borrow(hole, out);\n");
            }
            ExprKind::UnresolvedName { name, name_span } => {
                return Err(Error::at_span(
                    ErrorKind::UnknownPrimitive,
                    *name_span,
                    format!("unknown primitive '{name}'"),
                ));
            }
            ExprKind::Call {
                name,
                syntax,
                arguments,
                ..
            } => {
                let count = arguments.len();
                let result_type =
                    static_expression_type(expression, &self.parameter_types, placeholder_type)?;
                let result_scalar = match result_type {
                    Type::Scalar(scalar) | Type::Vector(scalar) => scalar_tag(scalar),
                    Type::Tuple(_) | Type::RepeatedTuple { .. } => return Err(emission_error()),
                };
                let metadata = emitted_semantic_metadata(*syntax, arguments);
                let anchor = metadata
                    .iter()
                    .position(|(_, length)| length.is_some())
                    .map_or("SIZE_MAX".to_owned(), |position| format!("{position}U"));
                writeln!(
                    self.definitions,
                    "  FWV args[{}U]; size_t initialized = 0U; int ok;",
                    count.max(1)
                )
                .map_err(|_| emission_error())?;
                self.definitions
                    .push_str("  (void)memset(args, 0, sizeof(args));\n");
                write!(
                    self.definitions,
                    "  const size_t origins[{}U][2] = {{",
                    metadata.len().max(1)
                )
                .map_err(|_| emission_error())?;
                for (location, _) in &metadata {
                    write!(
                        self.definitions,
                        "{{{}U,{}U}},",
                        location.line, location.column
                    )
                    .map_err(|_| emission_error())?;
                }
                if metadata.is_empty() {
                    self.definitions.push_str("{0U,0U}");
                }
                self.definitions.push_str("};\n");
                for (index, child) in child_ids.iter().enumerate() {
                    writeln!(
                        self.definitions,
                        "  if (!fw_expr_{child}(hole, &args[{index}U])) goto cleanup;\n  initialized = {next}U;",
                        next = index + 1
                    )
                    .map_err(|_| emission_error())?;
                }
                if *syntax == CallSyntax::Prefix && count == 1 {
                    writeln!(
                        self.definitions,
                        "  if (args[0].kind == 2) ok = fw_apply({}, {}, args[0].items, args[0].len, out, {}U, {}U, origins, {}U, {}); else ok = fw_apply({}, {}, args, 1U, out, {}U, {}U, origins, {}U, {});",
                        primitive_tag(name)?,
                        result_scalar,
                        expression.span.begin.line,
                        expression.span.begin.column,
                        metadata.len(),
                        anchor,
                        primitive_tag(name)?,
                        result_scalar,
                        expression.span.begin.line,
                        expression.span.begin.column,
                        metadata.len(),
                        anchor
                    )
                    .map_err(|_| emission_error())?;
                } else {
                    writeln!(
                        self.definitions,
                        "  ok = fw_apply({}, {}, args, {}U, out, {}U, {}U, origins, {}U, {});",
                        primitive_tag(name)?,
                        result_scalar,
                        count,
                        expression.span.begin.line,
                        expression.span.begin.column,
                        metadata.len(),
                        anchor
                    )
                    .map_err(|_| emission_error())?;
                }
                self.definitions.push_str(
                    "  while (initialized != 0U) fw_free(&args[--initialized]);\n  return ok;\ncleanup:\n  while (initialized != 0U) fw_free(&args[--initialized]);\n  return 0;\n",
                );
            }
            ExprKind::Fanout { branches, .. } => {
                let operand_id = child_ids[0];
                writeln!(
                    self.definitions,
                    "  FWV operand = {{0}}; size_t initialized = 0U;\n  if (!fw_expr_{operand_id}(hole, &operand)) return 0;\n  if (!fw_make_tuple(out, {}U, \"fanout\", {}U, {}U)) {{ fw_free(&operand); return 0; }}",
                    branches.len(),
                    expression.span.begin.line,
                    expression.span.begin.column
                )
                .map_err(|_| emission_error())?;
                for (index, child) in child_ids.iter().skip(1).enumerate() {
                    writeln!(
                        self.definitions,
                        "  if (!fw_expr_{child}(&operand, &out->items[{index}U])) goto fanout_cleanup;\n  initialized = {next}U;",
                        next = index + 1
                    )
                    .map_err(|_| emission_error())?;
                }
                self.definitions.push_str(
                    "  (void)initialized; fw_free(&operand); return 1;\nfanout_cleanup:\n  (void)initialized; fw_free(out); fw_free(&operand); return 0;\n",
                );
            }
        }
        self.definitions.push_str("}\n");
        Ok(id)
    }

    fn emit_literal(&mut self, value: &Value) -> Result<(), Error> {
        self.definitions.push_str("  (void)hole; ");
        match value {
            Value::Bool(value) => writeln!(
                self.definitions,
                "fw_set_bool(out, {}); return 1;",
                i32::from(*value)
            ),
            Value::Int(value) => writeln!(
                self.definitions,
                "fw_set_int(out, {}); return 1;",
                c_int64(*value)
            ),
            Value::Double(value) => writeln!(
                self.definitions,
                "fw_set_double(out, fw_double_from_bits(UINT64_C(0x{:016x}))); return 1;",
                value.to_bits()
            ),
            Value::BoolVector(_)
            | Value::IntVector(_)
            | Value::DoubleVector(_)
            | Value::Tuple(_) => return Err(emission_error()),
        }
        .map_err(|_| emission_error())
    }
}

const fn scalar_tag(scalar: ScalarType) -> i32 {
    match scalar {
        ScalarType::Bool => 0,
        ScalarType::Int => 1,
        ScalarType::Double => 2,
    }
}

fn primitive_tag(name: &str) -> Result<i32, Error> {
    match name {
        "inc" => Ok(0),
        "dec" => Ok(1),
        "neg" => Ok(2),
        "abs" => Ok(3),
        "add" => Ok(4),
        "sub" => Ok(5),
        "mul" => Ok(6),
        "equals" => Ok(7),
        "not_equals" => Ok(8),
        "not" => Ok(9),
        "and" => Ok(10),
        "or" => Ok(11),
        "odd" => Ok(12),
        "even" => Ok(13),
        "is_positive" => Ok(14),
        "is_negative" => Ok(15),
        "less_than" => Ok(16),
        "greater_than" => Ok(17),
        "iota" => Ok(18),
        _ => Err(emission_error()),
    }
}

fn vector_assignment(value: &Value, index: usize) -> Result<String, Error> {
    match value {
        Value::Bool(value) => Ok(format!(
            "((unsigned char *)out->data)[{index}U] = {}U",
            u8::from(*value)
        )),
        Value::Int(value) => Ok(format!(
            "((int64_t *)out->data)[{index}U] = {}",
            c_int64(*value)
        )),
        Value::Double(value) => Ok(format!(
            "((double *)out->data)[{index}U] = fw_double_from_bits(UINT64_C(0x{:016x}))",
            value.to_bits()
        )),
        Value::BoolVector(_) | Value::IntVector(_) | Value::DoubleVector(_) | Value::Tuple(_) => {
            Err(emission_error())
        }
    }
}

fn emitted_semantic_metadata(
    syntax: CallSyntax,
    arguments: &[Expr],
) -> Vec<(crate::SourceLocation, Option<usize>)> {
    let semantic: &[Expr] = if syntax == CallSyntax::Prefix && arguments.len() == 1 {
        match &arguments[0].kind {
            ExprKind::Tuple(elements) => elements,
            ExprKind::Fanout { branches, .. } => branches,
            _ => arguments,
        }
    } else {
        arguments
    };
    semantic
        .iter()
        .map(|expression| (expression.span.begin, known_vector_length(expression)))
        .collect()
}

fn static_expression_type(
    expression: &Expr,
    parameters: &[ScalarType],
    placeholder: Option<&Type>,
) -> Result<Type, Error> {
    match &expression.kind {
        ExprKind::Literal(value) => Ok(value.value_type()),
        ExprKind::Vector(scalar, _) => Ok(Type::Vector(*scalar)),
        ExprKind::Tuple(elements) => elements
            .iter()
            .map(|element| static_expression_type(element, parameters, placeholder))
            .collect::<Result<Vec<_>, _>>()
            .map(Type::Tuple),
        ExprKind::DeepTuple { depth, leaf } => Ok(Type::RepeatedTuple {
            depth: *depth,
            leaf: leaf.scalar_type().ok_or_else(emission_error)?,
        }),
        ExprKind::UnaryChain { leaf, steps, .. } => {
            let mut current = leaf.value_type();
            for step in steps {
                if step.name == "iota" {
                    current = Type::Vector(ScalarType::Int);
                    continue;
                }
                let scalar = if matches!(
                    step.name.as_str(),
                    "equals"
                        | "not_equals"
                        | "not"
                        | "and"
                        | "or"
                        | "odd"
                        | "even"
                        | "is_positive"
                        | "is_negative"
                        | "less_than"
                        | "greater_than"
                ) {
                    ScalarType::Bool
                } else if matches!(
                    current,
                    Type::Scalar(ScalarType::Double) | Type::Vector(ScalarType::Double)
                ) {
                    ScalarType::Double
                } else {
                    ScalarType::Int
                };
                current = if matches!(current, Type::Vector(_)) {
                    Type::Vector(scalar)
                } else {
                    Type::Scalar(scalar)
                };
            }
            Ok(current)
        }
        ExprKind::Parameter(index) => parameters
            .get(*index)
            .copied()
            .map(Type::Scalar)
            .ok_or_else(emission_error),
        ExprKind::Placeholder => placeholder.cloned().ok_or_else(emission_error),
        ExprKind::UnresolvedName { .. } => Err(emission_error()),
        ExprKind::Fanout { operand, branches } => {
            let operand_type = static_expression_type(operand, parameters, placeholder)?;
            branches
                .iter()
                .map(|branch| static_expression_type(branch, parameters, Some(&operand_type)))
                .collect::<Result<Vec<_>, _>>()
                .map(Type::Tuple)
        }
        ExprKind::Call {
            name,
            syntax,
            arguments,
            ..
        } => {
            let argument_types = arguments
                .iter()
                .map(|argument| static_expression_type(argument, parameters, placeholder))
                .collect::<Result<Vec<_>, _>>()?;
            let semantic = if *syntax == CallSyntax::Prefix
                && argument_types.len() == 1
                && let Type::Tuple(elements) = &argument_types[0]
            {
                elements.as_slice()
            } else {
                argument_types.as_slice()
            };
            if name == "iota" {
                return Ok(Type::Vector(ScalarType::Int));
            }
            let scalar = if matches!(
                name.as_str(),
                "equals"
                    | "not_equals"
                    | "not"
                    | "and"
                    | "or"
                    | "odd"
                    | "even"
                    | "is_positive"
                    | "is_negative"
                    | "less_than"
                    | "greater_than"
            ) {
                ScalarType::Bool
            } else if semantic.iter().any(|value_type| {
                matches!(
                    value_type,
                    Type::Scalar(ScalarType::Double) | Type::Vector(ScalarType::Double)
                )
            }) {
                ScalarType::Double
            } else {
                ScalarType::Int
            };
            if semantic
                .iter()
                .any(|value_type| matches!(value_type, Type::Vector(_)))
            {
                Ok(Type::Vector(scalar))
            } else {
                Ok(Type::Scalar(scalar))
            }
        }
    }
}

fn known_vector_length(expression: &Expr) -> Option<usize> {
    match &expression.kind {
        ExprKind::Vector(_, elements) => Some(elements.len()),
        ExprKind::Call {
            name,
            syntax,
            arguments,
            ..
        } if name != "iota" => emitted_semantic_metadata(*syntax, arguments)
            .into_iter()
            .find_map(|(_, length)| length),
        ExprKind::Literal(_)
        | ExprKind::Parameter(_)
        | ExprKind::DeepTuple { .. }
        | ExprKind::UnaryChain { .. }
        | ExprKind::UnresolvedName { .. }
        | ExprKind::Placeholder
        | ExprKind::Tuple(_)
        | ExprKind::Fanout { .. }
        | ExprKind::Call { .. } => None,
    }
}

fn c_int64(value: i64) -> String {
    if value == i64::MIN {
        "(-INT64_C(9223372036854775807) - INT64_C(1))".to_owned()
    } else {
        format!("INT64_C({value})")
    }
}

fn c_string(text: &str) -> String {
    let mut output = String::from("\"");
    for byte in text.bytes() {
        match byte {
            b'\\' => output.push_str("\\\\"),
            b'"' => output.push_str("\\\""),
            b'\n' => output.push_str("\\n"),
            b'\r' => output.push_str("\\r"),
            b'\t' => output.push_str("\\t"),
            0x20..=0x7e => output.push(char::from(byte)),
            _ => {
                let _ = write!(output, "\\{byte:03o}");
            }
        }
    }
    output.push('"');
    output
}

fn emission_error() -> Error {
    Error::new(
        ErrorKind::FormattingError,
        crate::SourceLocation::start(),
        "unable to construct generated C source",
    )
}

const PARAMETER_RUNTIME: &str = r#"/* Generated by Faraweave 0.1.0. Strict C11. */
#include <errno.h>
#include <inttypes.h>
#include <locale.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef _WIN32
#include <fcntl.h>
#include <io.h>
#endif
#if defined(__x86_64__) || defined(_M_X64)
#include <xmmintrin.h>
#endif

typedef struct FWV FWV;
struct FWV {
  int kind, type, owns, b;
  size_t len, charge, allocation_ordinal, cursor;
  int64_t i;
  double d;
  void *data;
  FWV *items;
  FWV *parent;
};
typedef int (*FWExpr)(const FWV *, FWV *);
extern FWV fw_parameters[];
extern const int fw_parameter_types[];
extern const char *const fw_parameter_names[];
extern const size_t fw_parameter_spans[][6];
extern const size_t fw_required;
extern const int fw_profile;
extern const int fw_has_vector_limit;
extern const size_t fw_vector_limit;
extern const int fw_has_tuple_limit;
extern const size_t fw_tuple_limit;
extern const int fw_has_live_limit;
extern const size_t fw_live_limit;
extern const int fw_has_work_limit;
extern const size_t fw_work_limit;
extern const int fw_has_failure_ordinal;
extern const size_t fw_failure_ordinal;
static const char *fw_error_kind = NULL;
static const char *fw_error_message = NULL;
static size_t fw_error_line = 1U, fw_error_column = 1U;
static char fw_error_storage[256];
static size_t fw_live_bytes=0U,fw_peak_live_bytes=0U,fw_work_units=0U;
static size_t fw_allocation_attempts=0U;

static int fw_fail(const char *kind, const char *message, size_t line, size_t column) {
  if (fw_error_kind == NULL) {
    fw_error_kind = kind; fw_error_message = message;
    fw_error_line = line == 0U ? 1U : line;
    fw_error_column = column == 0U ? 1U : column;
  }
  return 0;
}
static int fw_fail_primitive(const char *kind, const char *name, const char *reason,
                             size_t line, size_t column) {
  (void)snprintf(fw_error_storage, sizeof(fw_error_storage), "%s failed: %s", name, reason);
  return fw_fail(kind, fw_error_storage, line, column);
}
static int fw_fail_shape(const char *name, size_t argument, size_t expected,
                         size_t actual, size_t line, size_t column) {
  (void)snprintf(fw_error_storage, sizeof(fw_error_storage),
                 "%s argument %zu expected shape [%zu], got [%zu]",
                 name, argument, expected, actual);
  return fw_fail("ShapeMismatch", fw_error_storage, line, column);
}
static double fw_double_from_bits(uint64_t bits) {
  double value; (void)memcpy(&value, &bits, sizeof(value)); return value;
}
static uint64_t fw_double_bits(double value) {
  uint64_t bits; (void)memcpy(&bits, &value, sizeof(bits)); return bits;
}
static int fw_double_is_nan(double value) {
  uint64_t bits=fw_double_bits(value);
  return (bits&UINT64_C(0x7ff0000000000000))==UINT64_C(0x7ff0000000000000) &&
         (bits&UINT64_C(0x000fffffffffffff))!=UINT64_C(0);
}
static int fw_double_is_infinity(double value) {
  return (fw_double_bits(value)&UINT64_C(0x7fffffffffffffff))==UINT64_C(0x7ff0000000000000);
}
static int fw_double_is_zero(double value) {
  return (fw_double_bits(value)&UINT64_C(0x7fffffffffffffff))==UINT64_C(0);
}
static uint64_t fw_double_order_key(double value) {
  uint64_t bits=fw_double_bits(value);
  return (bits&UINT64_C(0x8000000000000000))!=UINT64_C(0)
      ?~bits:bits|UINT64_C(0x8000000000000000);
}
static int fw_double_equal(double left,double right) {
  if(fw_double_is_nan(left)||fw_double_is_nan(right))return 0;
  if(fw_double_is_zero(left)&&fw_double_is_zero(right))return 1;
  return fw_double_bits(left)==fw_double_bits(right);
}
static int fw_double_less_than(double left,double right) {
  if(fw_double_is_nan(left)||fw_double_is_nan(right)||
     (fw_double_is_zero(left)&&fw_double_is_zero(right)))return 0;
  return fw_double_order_key(left)<fw_double_order_key(right);
}
static double fw_int_to_double(int64_t value) {
  int negative=value<INT64_C(0); uint64_t magnitude,scan,significand=UINT64_C(0);
  uint64_t fraction,exponent; unsigned int most_significant=0U;
  if(value==INT64_C(0))return 0.0;
  magnitude=negative?(uint64_t)(-(value+INT64_C(1)))+UINT64_C(1):(uint64_t)value;
  scan=magnitude;while(scan>UINT64_C(1)){scan>>=1U;++most_significant;}
  if(most_significant<=52U)significand=magnitude<<(52U-most_significant);
  else {
    unsigned int shift=most_significant-52U;
    uint64_t mask=(UINT64_C(1)<<shift)-UINT64_C(1),remainder=magnitude&mask;
    uint64_t halfway=UINT64_C(1)<<(shift-1U);significand=magnitude>>shift;
    if(remainder>halfway||(remainder==halfway&&(significand&UINT64_C(1))!=0U)){
      ++significand;if(significand==(UINT64_C(1)<<53U)){significand>>=1U;++most_significant;}
    }
  }
  exponent=(uint64_t)(most_significant+1023U)<<52U;
  fraction=significand&UINT64_C(0x000fffffffffffff);
  return fw_double_from_bits((negative?UINT64_C(0x8000000000000000):UINT64_C(0))|
                             exponent|fraction);
}
#if defined(__x86_64__) || defined(_M_X64)
typedef struct FWStrictEnvironment {
  unsigned int control;
#if !defined(_MSC_VER)
  unsigned char x87[28];
#endif
} FWStrictEnvironment;
static void fw_begin_strict_environment(FWStrictEnvironment *environment) {
  environment->control=_mm_getcsr();
#if !defined(_MSC_VER)
  { uint16_t control=UINT16_C(0);
    __asm__ volatile("fnstenv %0":"=m"(environment->x87));
    (void)memcpy(&control,environment->x87,sizeof(control));
    control=(uint16_t)((control|UINT16_C(0x003f))&~UINT16_C(0x0c00));
    __asm__ volatile("fldcw %0"::"m"(control));
  }
#endif
  _mm_setcsr((environment->control|0x1f80U)&~(0x003fU|0x0040U|0x6000U|0x8000U));
}
static void fw_restore_strict_environment(const FWStrictEnvironment *environment) {
#if !defined(_MSC_VER)
  __asm__ volatile("fldenv %0"::"m"(environment->x87));
#endif
  _mm_setcsr(environment->control);
}
#elif defined(__aarch64__)
typedef struct FWStrictEnvironment { uint64_t control,status; } FWStrictEnvironment;
static void fw_begin_strict_environment(FWStrictEnvironment *environment) {
  uint64_t strict_control,clear_status=UINT64_C(0);
  __asm__ volatile("mrs %0, fpcr":"=r"(environment->control));
  __asm__ volatile("mrs %0, fpsr":"=r"(environment->status));
  strict_control=environment->control&
      ~(UINT64_C(0x00009f00)|UINT64_C(0x00c00000)|UINT64_C(0x03000000));
  __asm__ volatile("msr fpcr, %0\n\tisb"::"r"(strict_control):"memory");
  __asm__ volatile("msr fpsr, %0"::"r"(clear_status):"memory");
}
static void fw_restore_strict_environment(const FWStrictEnvironment *environment) {
  __asm__ volatile("msr fpcr, %0\n\tisb"::"r"(environment->control):"memory");
  __asm__ volatile("msr fpsr, %0"::"r"(environment->status):"memory");
}
#else
#error "Faraweave requires an x86-64 or AArch64 floating-point environment"
#endif
enum { FW_DOUBLE_ADD=0,FW_DOUBLE_SUB=1,FW_DOUBLE_MUL=2 };
static double fw_double_arithmetic(double left,double right,int operation) {
  uint64_t left_bits=fw_double_bits(left),right_bits=fw_double_bits(right);
  int signs_differ=((left_bits^right_bits)&UINT64_C(0x8000000000000000))!=0U;
  if(fw_double_is_nan(left)||fw_double_is_nan(right)||
     (fw_double_is_infinity(left)&&fw_double_is_infinity(right)&&
      ((operation==FW_DOUBLE_ADD&&signs_differ)||
       (operation==FW_DOUBLE_SUB&&!signs_differ)))||
     (operation==FW_DOUBLE_MUL&&
      ((fw_double_is_infinity(left)&&fw_double_is_zero(right))||
       (fw_double_is_zero(left)&&fw_double_is_infinity(right)))))
    return fw_double_from_bits(UINT64_C(0x7ff8000000000000));
  { FWStrictEnvironment environment;volatile double a=left,b=right,result=0.0;
    fw_begin_strict_environment(&environment);
    if(operation==FW_DOUBLE_ADD)result=a+b;
    else if(operation==FW_DOUBLE_SUB)result=a-b;
    else result=a*b;
    fw_restore_strict_environment(&environment);
    return fw_double_is_nan(result)
        ?fw_double_from_bits(UINT64_C(0x7ff8000000000000)):result;
  }
}
static void fw_set_bool(FWV *out, int value) {
  (void)memset(out, 0, sizeof(*out)); out->b = value != 0;
}
static void fw_set_int(FWV *out, int64_t value) {
  (void)memset(out, 0, sizeof(*out)); out->type = 1; out->i = value;
}
static void fw_set_double(FWV *out, double value) {
  (void)memset(out, 0, sizeof(*out)); out->type = 2;
  out->d = fw_double_is_nan(value)
      ? fw_double_from_bits(UINT64_C(0x7ff8000000000000)) : value;
}
static int fw_borrow(const FWV *value, FWV *out) {
  if (value == NULL) return 0;
  *out = *value; out->owns = 0; return 1;
}
static size_t fw_width(int type) { return type == 0 ? 1U : 8U; }
static int fw_fail_resource(const char *producer,const char *reason,
                            size_t line,size_t column) {
  (void)snprintf(fw_error_storage,sizeof(fw_error_storage),
                 "%s resource request failed: %s",producer,reason);
  return fw_fail("ResourceError",fw_error_storage,line,column);
}
static int fw_admit(size_t bytes,int tuple,size_t work,const char *producer,
                    size_t line,size_t column,size_t *ordinal) {
  size_t live_after,work_after;
  if(bytes>SIZE_MAX-fw_live_bytes||work>SIZE_MAX-fw_work_units)
    return fw_fail_resource(producer,"size_overflow",line,column);
  live_after=fw_live_bytes+bytes;work_after=fw_work_units+work;
  if((tuple?fw_has_tuple_limit:fw_has_vector_limit)&&
     bytes>(tuple?fw_tuple_limit:fw_vector_limit))
    return fw_fail_resource(producer,"profile_limit",line,column);
  if(fw_has_live_limit&&live_after>fw_live_limit)
    return fw_fail_resource(producer,"profile_limit",line,column);
  if(fw_has_work_limit&&work_after>fw_work_limit)
    return fw_fail_resource(producer,"profile_limit",line,column);
  *ordinal=SIZE_MAX;
  if(bytes!=0U){
    if(fw_allocation_attempts==SIZE_MAX)
      return fw_fail_resource(producer,"size_overflow",line,column);
    *ordinal=fw_allocation_attempts;++fw_allocation_attempts;
    if(fw_has_failure_ordinal&&*ordinal==fw_failure_ordinal)
      return fw_fail_resource(producer,"allocation_unavailable",line,column);
  }
  fw_live_bytes=live_after;fw_work_units=work_after;
  if(live_after>fw_peak_live_bytes)fw_peak_live_bytes=live_after;
  return 1;
}
static void fw_refund(size_t bytes) {
  fw_live_bytes=bytes<=fw_live_bytes?fw_live_bytes-bytes:0U;
}
static int fw_charge_work(size_t amount,const char *producer,size_t line,size_t column) {
  size_t after;if(amount>SIZE_MAX-fw_work_units)
    return fw_fail_resource(producer,"size_overflow",line,column);
  after=fw_work_units+amount;
  if(fw_has_work_limit&&after>fw_work_limit)
    return fw_fail_resource(producer,"profile_limit",line,column);
  fw_work_units=after;return 1;
}
static int fw_make_vector(FWV *out, int type, size_t length,size_t work,const char *producer,
                          size_t line,size_t column) {
  size_t bytes;
  (void)memset(out, 0, sizeof(*out)); out->kind = 1; out->type = type; out->len = length; out->owns = 1;
  if (length > SIZE_MAX / fw_width(type)) return fw_fail_resource(producer,"size_overflow",line,column);
  bytes=length*fw_width(type);
  if(!fw_admit(bytes,0,work,producer,line,column,&out->allocation_ordinal))return 0;
  if (length == 0U) return 1;
  out->data = calloc(length, fw_width(type));
  if(out->data==NULL){fw_refund(bytes);return fw_fail_resource(producer,"allocation_unavailable",line,column);}
  out->charge=bytes;return 1;
}
static int fw_make_tuple(FWV *out, size_t length,const char *producer,
                         size_t line,size_t column) {
  size_t bytes;
  (void)memset(out, 0, sizeof(*out)); out->kind = 2; out->len = length; out->owns = 1;
  if(fw_profile<2)return fw_fail("ProfileError",
      fw_profile==0?"trusted-local-v1 does not support value kind Tuple":
                    "bounded-v1 does not support value kind Tuple",line,column);
  if (length == 0U) return 1;
  if (length > SIZE_MAX / 16U || length > SIZE_MAX / sizeof(FWV))
    return fw_fail_resource(producer,"size_overflow",line,column);
  bytes=length*16U;
  if(!fw_admit(bytes,1,0U,producer,line,column,&out->allocation_ordinal))return 0;
  out->items = (FWV *)calloc(length, sizeof(FWV));
  if(out->items==NULL){fw_refund(bytes);return fw_fail_resource(producer,"allocation_unavailable",line,column);}
  out->charge=bytes;return 1;
}
static void fw_free(FWV *value) {
  FWV *current=value,*parent;void *storage;size_t charge;
  if(current!=NULL)current->parent=NULL;
  while(current!=NULL){
    if(!current->owns){
      parent=current->parent;(void)memset(current,0,sizeof(*current));current=parent;continue;
    }
    if(current->kind==2&&current->cursor<current->len){
      FWV *child=&current->items[current->len-1U-current->cursor++];
      child->parent=current;current=child;continue;
    }
    parent=current->parent;charge=current->charge;
    storage=current->kind==2?(void *)current->items:current->data;
    free(storage);(void)memset(current,0,sizeof(*current));fw_refund(charge);
    current=parent;
  }
}
static FWV fw_scalar_at(const FWV *value, size_t index) {
  FWV result = {0};
  result.type = value->type;
  if (value->kind == 0) return *value;
  if (value->type == 0) result.b = ((const unsigned char *)value->data)[index] != 0U;
  else if (value->type == 1) result.i = ((const int64_t *)value->data)[index];
  else result.d = ((const double *)value->data)[index];
  return result;
}
static int fw_put_scalar(FWV *value, size_t index, FWV scalar) {
  if (value->kind == 0) { *value = scalar; return 1; }
  if (value->type == 0) ((unsigned char *)value->data)[index] = (unsigned char)scalar.b;
  else if (value->type == 1) ((int64_t *)value->data)[index] = scalar.i;
  else ((double *)value->data)[index] = scalar.d;
  return 1;
}
static double fw_as_double(FWV value) {
  return value.type == 2 ? value.d : fw_int_to_double(value.i);
}
enum {
  FW_INC,FW_DEC,FW_NEG,FW_ABS,FW_ADD,FW_SUB,FW_MUL,FW_EQUALS,FW_NOT_EQUALS,
  FW_NOT,FW_AND,FW_OR,FW_ODD,FW_EVEN,FW_IS_POSITIVE,FW_IS_NEGATIVE,
  FW_LESS_THAN,FW_GREATER_THAN,FW_IOTA
};
static const char *fw_primitive_name(int primitive) {
  static const char *const names[]={
    "inc","dec","neg","abs","add","sub","mul","equals","not_equals","not",
    "and","or","odd","even","is_positive","is_negative","less_than",
    "greater_than","iota"
  };
  return primitive>=FW_INC&&primitive<=FW_IOTA?names[primitive]:"invalid";
}
static int fw_apply_scalar(int primitive, const FWV *args, size_t count, int result_type,
                           FWV *out, size_t line, size_t column, size_t index,
                           int vector_result) {
  const char *name=fw_primitive_name(primitive);
  int64_t a, b; double x, y;
  if (primitive==FW_NOT) { fw_set_bool(out, !args[0].b); return 1; }
  if (primitive==FW_AND) { fw_set_bool(out, args[0].b && args[1].b); return 1; }
  if (primitive==FW_OR) { fw_set_bool(out, args[0].b || args[1].b); return 1; }
  if (primitive==FW_ODD) { fw_set_bool(out, args[0].i % 2 != 0); return 1; }
  if (primitive==FW_EVEN) { fw_set_bool(out, args[0].i % 2 == 0); return 1; }
  if (result_type == 1) {
    a = args[0].i; b = count > 1U ? args[1].i : 0;
    if (primitive==FW_INC) { if (a == INT64_MAX) goto overflow; fw_set_int(out, a + 1); return 1; }
    if (primitive==FW_DEC) { if (a == INT64_MIN) goto overflow; fw_set_int(out, a - 1); return 1; }
    if (primitive==FW_NEG) { if (a == INT64_MIN) goto overflow; fw_set_int(out, -a); return 1; }
    if (primitive==FW_ABS) { if (a == INT64_MIN) goto overflow; fw_set_int(out, a < 0 ? -a : a); return 1; }
    if (primitive==FW_ADD) { if ((b > 0 && a > INT64_MAX-b)||(b < 0 && a < INT64_MIN-b)) goto overflow; fw_set_int(out,a+b); return 1; }
    if (primitive==FW_SUB) { if ((b < 0 && a > INT64_MAX+b)||(b > 0 && a < INT64_MIN+b)) goto overflow; fw_set_int(out,a-b); return 1; }
    if (primitive==FW_MUL) {
      if (a != 0 && ((a == -1 && b == INT64_MIN) || (b == -1 && a == INT64_MIN) ||
          (a > 0 && ((b > 0 && a > INT64_MAX/b)||(b < 0 && b < INT64_MIN/a))) ||
          (a < 0 && ((b > 0 && a < INT64_MIN/b)||(b < 0 && a < INT64_MAX/b))))) goto overflow;
      fw_set_int(out,a*b); return 1;
    }
  }
  if (result_type == 2) {
    x = fw_as_double(args[0]); y = count > 1U ? fw_as_double(args[1]) : 0.0;
    if (primitive==FW_INC) { fw_set_double(out,fw_double_arithmetic(x,1.0,FW_DOUBLE_ADD)); return 1; }
    if (primitive==FW_DEC) { fw_set_double(out,fw_double_arithmetic(x,1.0,FW_DOUBLE_SUB)); return 1; }
    if (primitive==FW_NEG) { fw_set_double(out,fw_double_from_bits(fw_double_bits(x)^UINT64_C(0x8000000000000000))); return 1; }
    if (primitive==FW_ABS) { fw_set_double(out,fw_double_from_bits(fw_double_bits(x)&UINT64_C(0x7fffffffffffffff))); return 1; }
    if (primitive==FW_ADD) { fw_set_double(out,fw_double_arithmetic(x,y,FW_DOUBLE_ADD)); return 1; }
    if (primitive==FW_SUB) { fw_set_double(out,fw_double_arithmetic(x,y,FW_DOUBLE_SUB)); return 1; }
    if (primitive==FW_MUL) { fw_set_double(out,fw_double_arithmetic(x,y,FW_DOUBLE_MUL)); return 1; }
  }
  if (primitive==FW_EQUALS || primitive==FW_NOT_EQUALS) {
    int equal;
    if(args[0].type==0)equal=args[0].b==args[1].b;
    else if(args[0].type==1&&args[1].type==1)equal=args[0].i==args[1].i;
    else equal=fw_double_equal(fw_as_double(args[0]),fw_as_double(args[1]));
    fw_set_bool(out, primitive==FW_EQUALS ? equal : !equal); return 1;
  }
  if (primitive==FW_IS_POSITIVE) { fw_set_bool(out,args[0].type==1?args[0].i>0:
      !fw_double_is_nan(args[0].d)&&!fw_double_is_zero(args[0].d)&&
      (fw_double_bits(args[0].d)&UINT64_C(0x8000000000000000))==0U); return 1; }
  if (primitive==FW_IS_NEGATIVE) { fw_set_bool(out,args[0].type==1?args[0].i<0:
      !fw_double_is_nan(args[0].d)&&!fw_double_is_zero(args[0].d)&&
      (fw_double_bits(args[0].d)&UINT64_C(0x8000000000000000))!=0U); return 1; }
  if (primitive==FW_LESS_THAN || primitive==FW_GREATER_THAN) {
    int less=args[0].type==1&&args[1].type==1?args[0].i<args[1].i:
      fw_double_less_than(fw_as_double(args[0]),fw_as_double(args[1]));
    int greater=args[0].type==1&&args[1].type==1?args[0].i>args[1].i:
      fw_double_less_than(fw_as_double(args[1]),fw_as_double(args[0]));
    fw_set_bool(out,primitive==FW_LESS_THAN?less:greater);return 1;
  }
  return fw_fail("ValueError","invalid primitive invocation",line,column);
overflow:
  if(vector_result){
    (void)snprintf(fw_error_storage,sizeof(fw_error_storage),
                   "%s failed: integer_overflow at result index %zu",name,index);
    return fw_fail("DomainError",fw_error_storage,line,column);
  }
  return fw_fail_primitive("DomainError",name,"integer_overflow",line,column);
}
static int fw_apply(int primitive, int result_type, const FWV *args, size_t count, FWV *out,
                    size_t line, size_t column,const size_t (*origins)[2],
                    size_t origin_count,size_t static_anchor) {
  const char *name=fw_primitive_name(primitive);
  size_t i, length = 1U,anchor=SIZE_MAX; int vector = 0;
  if (primitive==FW_IOTA) {
    int64_t bound;
    if (count != 1U || args[0].kind != 0 || args[0].type != 1) return fw_fail("TypeError","iota arguments do not match an accepted signature",line,column);
    bound = args[0].i; length = bound > 0 ? (size_t)bound : 0U;
    if (!fw_make_vector(out,1,length,length,name,line,column)) return 0;
    for (i=0U;i<length;++i) ((int64_t *)out->data)[i]=(int64_t)i+1;
    return 1;
  }
  for (i=0U;i<count;++i) {
    if (args[i].kind==2) return fw_fail("TypeError","tuple argument is not accepted",line,column);
    if (args[i].kind==1)vector=1;
  }
  if(vector){
    if(static_anchor<count&&args[static_anchor].kind==1)anchor=static_anchor;
    else for(i=0U;i<count;++i)if(args[i].kind==1){anchor=i;break;}
    length=args[anchor].len;
    for(i=0U;i<count;++i)if(i!=anchor&&args[i].kind==1&&args[i].len!=length){
      size_t origin_line=i<origin_count?origins[i][0]:line;
      size_t origin_column=i<origin_count?origins[i][1]:column;
      return fw_fail_shape(name,i+1U,length,args[i].len,origin_line,origin_column);
    }
  }
  if (vector) { if (!fw_make_vector(out,result_type,length,length,name,line,column)) return 0; }
  else { (void)memset(out,0,sizeof(*out)); out->type=result_type; }
  if(!vector&&!fw_charge_work(length,name,line,column))return 0;
  for (i=0U;i<length;++i) {
    FWV scalar_args[2]={{0}}; FWV scalar_out={0}; size_t j;
    for(j=0U;j<count;++j) scalar_args[j]=fw_scalar_at(&args[j],i);
    if(!fw_apply_scalar(primitive,scalar_args,count,result_type,&scalar_out,line,column,i,vector)) { fw_free(out); return 0; }
    (void)fw_put_scalar(out,i,scalar_out);
  }
  return 1;
}
typedef struct { char *data; size_t size, capacity; } FWBuffer;
static int fw_append(FWBuffer *buffer,const char *text) {
  size_t n=strlen(text),needed; char *grown;
  if(n>SIZE_MAX-buffer->size-1U) return 0;
  needed=buffer->size+n+1U;
  if(needed>buffer->capacity) { size_t next=buffer->capacity?buffer->capacity:128U;
    while(next<needed){if(next>SIZE_MAX/2U)return 0;next*=2U;}
    grown=(char *)realloc(buffer->data,next);if(grown==NULL)return 0;buffer->data=grown;buffer->capacity=next;}
  (void)memcpy(buffer->data+buffer->size,text,n+1U);buffer->size+=n;return 1;
}
static void fw_normalize_exponent(const char *input,char *output,size_t capacity) {
  const char *exponent=strchr(input,'e'),*upper=strchr(input,'E'),*digits;
  size_t used=0U;int negative=0;
  if(exponent==NULL)exponent=upper;
  if(exponent==NULL){(void)snprintf(output,capacity,"%s",input);return;}
  while(input!=exponent&&used+1U<capacity)output[used++]=*input++;
  if(used+1U<capacity)output[used++]='e';
  digits=exponent+1;if(*digits=='+'||*digits=='-'){negative=*digits=='-';++digits;}
  while(digits[0]=='0'&&digits[1]!='\0')++digits;
  if(negative&&used+1U<capacity)output[used++]='-';
  while(*digits!='\0'&&used+1U<capacity)output[used++]=*digits++;
  output[used]='\0';
}
static int fw_format_double(char *output,size_t capacity,double value) {
  uint64_t bits=fw_double_bits(value);double magnitude;
  char candidate[64],normalized[64];int precision,matched=0,ok=0;
  FWStrictEnvironment environment;
  if(fw_double_is_nan(value)){(void)snprintf(output,capacity,"nan");return 1;}
  if(fw_double_is_infinity(value)){
    (void)snprintf(output,capacity,"%s",(bits&UINT64_C(0x8000000000000000))?"-inf":"inf");
    return 1;
  }
  if(bits==UINT64_C(0)){(void)snprintf(output,capacity,"0.0");return 1;}
  if(bits==UINT64_C(0x8000000000000000)){(void)snprintf(output,capacity,"-0.0");return 1;}
  magnitude=fw_double_from_bits(bits&UINT64_C(0x7fffffffffffffff));candidate[0]='\0';
  fw_begin_strict_environment(&environment);
  if(magnitude>=1000000.0||magnitude<0.0001){
    for(precision=0;precision<=16;++precision){
      char *end=NULL;double parsed;
      if(snprintf(candidate,sizeof(candidate),"%.*e",precision,value)<0)goto done;
      parsed=strtod(candidate,&end);
      if(end!=NULL&&*end=='\0'&&fw_double_bits(parsed)==bits){matched=1;break;}
    }
  }else{
    for(precision=0;precision<=20;++precision){
      char *end=NULL;double parsed;
      if(snprintf(candidate,sizeof(candidate),"%.*f",precision,value)<0)goto done;
      parsed=strtod(candidate,&end);
      if(end!=NULL&&*end=='\0'&&fw_double_bits(parsed)==bits){matched=1;break;}
    }
  }
  if(!matched)goto done;
  fw_normalize_exponent(candidate,normalized,sizeof(normalized));
  if(strchr(normalized,'.')==NULL&&strchr(normalized,'e')==NULL){
    if(snprintf(output,capacity,"%s.0",normalized)<0)goto done;
  }else if(snprintf(output,capacity,"%s",normalized)<0)goto done;
  ok=1;
done:
  fw_restore_strict_environment(&environment);return ok;
}
typedef struct { const FWV *value; size_t index; } FWFormatFrame;
static int fw_format(FWBuffer *buffer,const FWV *value) {
  FWFormatFrame *stack=NULL,*grown;size_t depth=0U,capacity=0U,i;char text[128];int ok=0;
  if(capacity==depth){capacity=16U;stack=(FWFormatFrame *)malloc(capacity*sizeof(*stack));if(stack==NULL)return 0;}
  stack[depth++]=(FWFormatFrame){value,0U};
  while(depth!=0U){
    FWFormatFrame *frame=&stack[depth-1U];const FWV *current=frame->value;
    if(current->kind==2){
      if(frame->index==0U&&!fw_append(buffer,"["))goto done;
      if(frame->index<current->len){
        const FWV *child=&current->items[frame->index];
        if(frame->index!=0U&&!fw_append(buffer," "))goto done;
        ++frame->index;
        if(depth==capacity){
          size_t next;if(capacity>SIZE_MAX/2U)goto done;next=capacity*2U;
          if(next>SIZE_MAX/sizeof(*stack))goto done;
          grown=(FWFormatFrame *)realloc(stack,next*sizeof(*stack));if(grown==NULL)goto done;
          stack=grown;capacity=next;
        }
        stack[depth++]=(FWFormatFrame){child,0U};continue;
      }
      if(!fw_append(buffer,"]"))goto done;
      --depth;continue;
    }
    if(current->kind==1){
      if(!fw_append(buffer,"("))goto done;
      for(i=0U;i<current->len;++i){
        FWV scalar=fw_scalar_at(current,i);
        if(i!=0U&&!fw_append(buffer," "))goto done;
        if(scalar.type==0){if(!fw_append(buffer,scalar.b?"true":"false"))goto done;}
        else if(scalar.type==1){if(snprintf(text,sizeof(text),"%" PRId64,scalar.i)<=0||!fw_append(buffer,text))goto done;}
        else if(!fw_format_double(text,sizeof(text),scalar.d)||!fw_append(buffer,text))goto done;
      }
      if(!fw_append(buffer,")"))goto done;
      --depth;continue;
    }
    if(current->type==0){if(!fw_append(buffer,current->b?"true":"false"))goto done;}
    else if(current->type==1){if(snprintf(text,sizeof(text),"%" PRId64,current->i)<=0||!fw_append(buffer,text))goto done;}
    else if(!fw_format_double(text,sizeof(text),current->d)||!fw_append(buffer,text))goto done;
    --depth;
  }
  ok=1;
done:
  free(stack);return ok;
}
static int fw_ascii_digits(const char *text) {
  if(*text=='\0')return 0;
  while(*text!='\0'){if(*text<'0'||*text>'9')return 0;++text;}return 1;
}
static int fw_finite_double_grammar(const char *text) {
  const char *cursor=text,*integer;size_t integer_count=0U;int fraction=0,exponent=0;
  if(*cursor=='-')++cursor;else if(*cursor=='+')return 0;
  integer=cursor;while(*cursor>='0'&&*cursor<='9'){++integer_count;++cursor;}
  if(integer_count==0U||(integer[0]=='0'&&integer_count!=1U))return 0;
  if(*cursor=='.'){
    ++cursor;while(*cursor>='0'&&*cursor<='9'){fraction=1;++cursor;}
    if(!fraction)return 0;
  }
  if(*cursor=='e'||*cursor=='E'){
    ++cursor;if(*cursor=='+'||*cursor=='-')++cursor;
    while(*cursor>='0'&&*cursor<='9'){exponent=1;++cursor;}
    if(!exponent)return 0;
  }
  return *cursor=='\0'&&(fraction||exponent);
}
enum { FW_DECODE_INVALID=0,FW_DECODE_OK=1,FW_DECODE_RANGE=2 };
static int fw_decode(const char *text,int type,FWV *out) {
  char *end=NULL;
  if(type==0){if(strcmp(text,"true")==0){fw_set_bool(out,1);return FW_DECODE_OK;}if(strcmp(text,"false")==0){fw_set_bool(out,0);return FW_DECODE_OK;}return FW_DECODE_INVALID;}
  if(type==1){
    const char *digits=*text=='-'?text+1:text;
    if(!fw_ascii_digits(digits)||*text=='+'||(digits[0]=='0'&&digits[1]!='\0')||
       (*text=='-'&&digits[0]=='0'&&digits[1]=='\0'))return FW_DECODE_INVALID;
    errno=0;out->i=strtoimax(text,&end,10);out->type=1;
    return errno==ERANGE||end==text||*end!='\0'?FW_DECODE_RANGE:FW_DECODE_OK;
  }
  if(strcmp(text,"inf")==0){fw_set_double(out,fw_double_from_bits(UINT64_C(0x7ff0000000000000)));return 1;}
  if(strcmp(text,"-inf")==0){fw_set_double(out,fw_double_from_bits(UINT64_C(0xfff0000000000000)));return 1;}
  if(strcmp(text,"nan")==0){fw_set_double(out,fw_double_from_bits(UINT64_C(0x7ff8000000000000)));return 1;}
  if(!fw_finite_double_grammar(text))return FW_DECODE_INVALID;
  { FWStrictEnvironment environment;errno=0;
    fw_begin_strict_environment(&environment);
    out->d=strtod(text,&end);
    fw_restore_strict_environment(&environment);out->type=2;
    return end==text||*end!='\0'||fw_double_is_infinity(out->d)
        ?FW_DECODE_RANGE:FW_DECODE_OK;
  }
}
static const char *fw_type_name(int type) {
  return type==0?"Bool":type==1?"Int":"Double";
}
static int fw_report_argument(const char *reason,size_t supplied,size_t position) {
  if(position<=fw_required){
    const size_t *span=fw_parameter_spans[position-1U];
    return fprintf(stderr,
      "faraweave_argument_error reason=%s required_count=%zu supplied_count=%zu position=%zu parameter_name=%s expected_type=%s declaration_span=%zu:%zu:%zu-%zu:%zu:%zu actual_container=- actual_type=- invalid_value_invariant=-\n",
      reason,fw_required,supplied,position,fw_parameter_names[position-1U],
      fw_type_name(fw_parameter_types[position-1U]),span[0],span[1],span[2],
      span[3],span[4],span[5])<0?0:1;
  }
  return fprintf(stderr,
    "faraweave_argument_error reason=%s required_count=%zu supplied_count=%zu position=%zu parameter_name=- expected_type=- declaration_span=- actual_container=- actual_type=- invalid_value_invariant=-\n",
    reason,fw_required,supplied,position)<0?0:1;
}
static int fw_main(int argc,char **argv,size_t root_count,const FWExpr *roots) {
  size_t supplied=argc>0?(size_t)argc-1U:0U,i,initialized=0U;FWV *values=NULL;FWBuffer output={0};int decoded;
  (void)fw_apply;
  (void)fw_make_tuple;
#ifdef _WIN32
  if (_setmode(_fileno(stdout), _O_BINARY) == -1 || _setmode(_fileno(stderr), _O_BINARY) == -1) return 1;
#endif
  if(setvbuf(stdout,NULL,_IONBF,0)!=0)return 1;
  if(setlocale(LC_NUMERIC,"C")==NULL)return 1;
  if(supplied!=fw_required){size_t pos=supplied<fw_required?supplied+1U:fw_required+1U;(void)fw_report_argument(supplied<fw_required?"missing":"extra",supplied,pos);return 1;}
  for(i=0U;i<fw_required;++i){decoded=fw_decode(argv[i+1U],fw_parameter_types[i],&fw_parameters[i]);if(decoded!=FW_DECODE_OK){(void)fw_report_argument(decoded==FW_DECODE_RANGE?"out_of_range":"invalid_literal",supplied,i+1U);return 1;}}
  values=(FWV *)calloc(root_count?root_count:1U,sizeof(FWV));if(values==NULL)return 1;
  for(i=0U;i<root_count;++i){if(!roots[i](NULL,&values[i]))goto failure;initialized=i+1U;}
  for(i=0U;i<root_count;++i)if(!fw_format(&output,&values[i])||!fw_append(&output,"\n"))goto failure;
  while(initialized)fw_free(&values[--initialized]);
  free(values);
  if(output.size){size_t accepted=fwrite(output.data,1U,output.size,stdout);
    if(accepted!=output.size){(void)fprintf(stderr,
      "faraweave_output_error reason=write_failed pending_byte_count=%zu accepted_byte_count=%zu output_position=%zu\n",
      output.size,accepted,accepted);free(output.data);return 1;}}
  {size_t published=output.size;free(output.data);
    if(fflush(stdout)!=0){(void)fprintf(stderr,
      "faraweave_output_error reason=flush_failed pending_byte_count=%zu accepted_byte_count=%zu output_position=%zu\n",
      published,published,published);return 1;}}return 0;
failure:
  while(initialized)fw_free(&values[--initialized]);
  free(values);free(output.data);
  (void)fprintf(stderr,"<generated>:%zu:%zu: %s: %s\n",fw_error_line,fw_error_column,fw_error_kind?fw_error_kind:"FormattingError",fw_error_message?fw_error_message:"unable to format result");return 1;
}
"#;
